apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.datapower_instance.name }}-svc
  labels:
    app.kubernetes.io/component: datapower
    app.kubernetes.io/instance: {{ .Values.datapower_instance.namespace }}-dp
    app.kubernetes.io/managed-by: datapower-operator
    app.kubernetes.io/name: datapower
    app.kubernetes.io/part-of: ibm-datapower-dp
spec:
  ports:
    - name: rmi-port
      protocol: TCP
      port: 5554
      targetPort: 5554
    - name: xmi-port
      protocol: TCP
      port: 5550
      targetPort: 5550
    - name: webgui-port
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: api-traffic-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:          # Ensure the selectors match the labels of the DataPower pod.
    app.kubernetes.io/component: datapower
    app.kubernetes.io/instance: {{ .Values.datapower_instance.namespace }}-dp
    app.kubernetes.io/managed-by: datapower-operator
    app.kubernetes.io/name: datapower
    app.kubernetes.io/part-of: ibm-datapower-dp
    statefulset.kubernetes.io/pod-name: {{ .Values.datapower_instance.name }}-0
  sessionAffinity: None
  type: ClusterIP